# docker-compose.yml

version: '3.8'

services:
  elasticsearch:
    # command 대신 build 섹션을 사용하여 위에서 만든 Dockerfile을 지정합니다.
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    container_name: blog-search-es
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local